language: java
jdk:
  - oraclejdk7
  - oraclejdk8
addons:
  apt:
    packages:
      - rpm
before_deploy:
  - mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
  - mvn rpm:rpm && export RELEASE_RPM_FILE=$(ls target/rpm/alarmcallback-jabber/RPMS/noarch/alarmcallback-jabber-*.rpm)
  - export RELEASE_PKG_FILE=$(ls target/alarmcallback-*.jar)
  - echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: Sjdiq2CjrhGRcMosalb5hz+nQhHYwBa2sA22v43S3hsVi5MSpC2OSp/ycOTf7d4BekuyDjbE3npEnAm6zUmbMl2g9ENapK6kb1YNYZBR6MSEdDwC6+3dDU2kAXoMKmFzdZRW0ArrPXzYOqQcyn2l1zvriFRJYVWdc1e6lPLF6YE=
  file: 
    - "${RELEASE_PKG_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk7
